Задание 1

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)

Задание 2

In [3]:
a11 = a.reshape(2, 6)
a12 = a.reshape(3, 4)
a13 = a.reshape(4, 3)
a14 = a.reshape(6, 2)
a15 = a.reshape(12, 1)

Задание 3

In [4]:
a21 = a.reshape(-1, 6)
a22 = a.reshape(-1, 4)
a23 = a.reshape(4, -1)
a24 = a.reshape(6, -1)
a25 = a.reshape(12, -1)

Задание 4. Ответ - нельзя.

Задание 5

In [5]:
n = np.random.randn(3, 4)
n.flatten()

array([ 2.06074377, -0.22294623,  0.16909804,  2.62961487, -0.61974692,
        0.30983465, -0.11451233,  1.55548186, -1.28149209,  1.02773755,
       -1.30060366, -1.00550815])

Задание 6

In [6]:
a = np.arange(20, 1, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7

In [7]:
b = np.array([[i for i in range(20, 1, -2)]])
b
#a - это одномерный массив, b - двумерный массив с одной строкой

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Задание 8

In [8]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size

10

Задание 9

In [9]:
a = np.arange(12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
np.linalg.det(B) #Посчитать обратную матрицу для B невозможно, так как её определитель равен нулю.

0.0

Задание 10

In [10]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

Задание 11

In [11]:
c = np.random.permutation(np.arange(16))

Задание 12

In [12]:
C = c.reshape(4, 4)
D = C * 10 + B

print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))

D_inv = np.linalg.inv(D)
D_inv

95676799.99999991
4


array([[-0.00462599, -0.02290503,  0.02203209, -0.00340187],
       [ 0.01351362, -0.06701123,  0.0359734 ,  0.00301494],
       [-0.0022229 ,  0.04233294, -0.02225534, -0.00279148],
       [-0.00316336,  0.01024303, -0.00859414,  0.00371982]])

Задание 13

In [13]:
D_inv[D_inv <= 0] = 0
D_inv[D_inv > 0] = 1

E = np.ones((4, 4))
np.putmask(E, D_inv, B)
np.putmask(E, D_inv == 0, C)
E

array([[  0.,  10.,  23.,   1.],
       [ 14.,   5.,  86., 122.],
       [ 14.,  86.,  13.,   2.],
       [  9., 122.,   4., 302.]])